"use client";
import { ArrowDownRight, ArrowRight, ArrowUpRight, Eye, EyeOff, Layers3, Plus } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import { useDesk } from "../../providers/desk-provider";
import { DeskChart } from "../market/desk-chart";
import { companies, stocks } from "../market/catalog";
import { demoChanges } from "../market/preview";
import { StockLogo } from "../market/stock-logo";
import { automationPresets, kindName } from "../strategies/automation-catalog";
import { StrategyGlyph } from "../strategies/strategy-glyph";
import { accountValue, availableCash } from "../trading/ledger";
import { demoQuote, usd } from "../trading/market-data";
export function OverviewView(){
  const {state,toggleBalance}=useDesk();const [period,setPeriod]=useState("1D");
  const bots=state.automations.filter(a=>a.status!=="archived");
  const invested=state.holdings.reduce((n,h)=>n+h.costCents,0);
  const gain=accountValue(state)-state.cashCents-invested;
  return <div className="desk-overview">
    <div className="desk-page-title"><div><span className="desk-overline">A CLEARER VIEW</span><h1>Your capital. In motion<span>.</span></h1><p>A place for every position. A plan for your next move.</p></div><Link className="desk-button primary" href="/automations?preview=1&new=dca"><Plus size={16}/>Create automation</Link></div>
    <div className="overview-hero-grid">
      <section className="capital-panel"><div className="capital-top"><span>Demo portfolio value<button type="button" onClick={toggleBalance} aria-label={state.hideBalance?"Show balance":"Hide balance"}>{state.hideBalance?<EyeOff size={15}/>:<Eye size={15}/>}</button></span><span className="capital-badge"><i/>PAPER WORKSPACE</span></div><div className="capital-value">{state.hideBalance?"••,•••.••":usd(accountValue(state))}<span>USD</span></div><div className="capital-performance"><span><ArrowUpRight size={14}/>{state.hideBalance?"•••":usd(gain)}</span><span>unrealized · sample holdings</span></div><div className="capital-chart"><DeskChart dark symbol="NVDAc" period={period}/></div><div className="capital-foot"><span><i/>Illustrative trend</span><div className="desk-periods">{["1D","1W","1M","1Y"].map(p=><button type="button" key={p} aria-pressed={p===period} className={p===period?"active":""} onClick={()=>setPeriod(p)}>{p}</button>)}</div></div></section>
      <section className="next-move-panel"><div className="next-move-top"><span className="desk-overline">THE STRATEGY STUDIO</span><ArrowUpRight size={19}/></div><h2>A little less watching.<br/>A little more intention.</h2><p>Give your next trade a set of rules.</p><div className="studio-art"><div className="studio-art-orbit orbit-one"/><div className="studio-art-orbit orbit-two"/><div className="studio-art-tile tile-a"><StockLogo symbol="NVDAc"/></div><div className="studio-art-tile tile-b"><Layers3 size={26}/></div><div className="studio-art-tile tile-c"><StockLogo symbol="AAPLc"/></div><div className="studio-art-label"><i/>Your rules, connected.</div></div><Link className="desk-button dark" href="/automations?preview=1">Find your strategy<ArrowRight size={16}/></Link><div className="studio-footnote">DCA · Grid · Signals · Trailing exits</div></section>
    </div>
    <section className="desk-quick-stats" aria-label="Demo account summary"><div><span>Available cash</span><strong>{state.hideBalance?"••••":usd(availableCash(state))}</strong><small>USDC, ready for your next move</small></div><div><span>Invested in stocks</span><strong>{state.hideBalance?"••••":usd(accountValue(state)-state.cashCents)}</strong><small>{state.holdings.length} positions on Base</small></div><div><span>Active automations</span><strong>{bots.filter(a=>a.status==="running").length}<small> / {bots.length}</small></strong><small>Demo configurations</small></div><div><span>Open orders</span><strong>{state.orders.filter(o=>o.status==="open").length.toString().padStart(2,"0")}</strong><small>Paper orders awaiting a demo tick</small></div></section>
    <section className="desk-section"><div className="desk-section-heading"><div><span className="desk-overline">ON YOUR RADAR</span><h2>The names you know.</h2></div><Link className="desk-text-link" href="/markets?preview=1">All markets<ArrowUpRight size={15}/></Link></div><div className="desk-market-strip">{stocks.map(symbol=><Link key={symbol} href={`/trade?preview=1&symbol=${symbol}`} className="desk-market-tile"><div><StockLogo symbol={symbol}/><span><strong>{companies[symbol]?.name}</strong><small>{symbol} / USDC</small></span><ArrowUpRight size={14}/></div><div className="desk-market-tile-bottom"><strong>{usd(demoQuote(symbol,state.tick))}</strong><span className={(demoChanges[symbol]??0)>0?"desk-positive":"desk-negative"}>{(demoChanges[symbol]??0)>0?<ArrowUpRight size={12}/>:<ArrowDownRight size={12}/>} {Math.abs(demoChanges[symbol]??0)}%</span></div><DeskChart compact symbol={symbol}/></Link>)}</div></section>
    <div className="overview-lower-grid"><section className="desk-surface"><div className="desk-section-heading inset"><div><span className="desk-overline">WORKING FOR YOU</span><h2>Your automations</h2></div><Link className="desk-text-link" href="/automations?preview=1">Manage<ArrowUpRight size={15}/></Link></div>{bots.slice(0,3).map(bot=><Link key={bot.id} className="overview-bot-row" href={`/automations?preview=1&inspect=${bot.id}`}><span className={`mini-strategy-icon tone-${bot.kind}`}><Layers3 size={17}/></span><div><strong>{bot.name}</strong><small>{kindName[bot.kind]} · {bot.symbol}</small></div><span>{usd(bot.budgetCents)}<small>budget limit</small></span><span className={`desk-status ${bot.status}`}><i/>{bot.status==="running"?"Demo enabled":"Paused"}</span></Link>)}{bots.length===0&&<div className="desk-empty">A fresh start. Create your first automation.</div>}</section><section className="desk-signal-feature"><span className="desk-overline">LESS NOISE. MORE CONTEXT.</span><div className="signal-feature-graphic"><StrategyGlyph kind="signal"/></div><h2>Find the moment.<br/>Keep the context.</h2><p>Explore sample signals with an entry, an exit, and room to decide.</p><Link className="desk-text-link" href="/signals?preview=1">Explore signals<ArrowRight size={16}/></Link></section></div>
    <section className="desk-section"><div className="desk-section-heading"><div><span className="desk-overline">START WITH A FRAMEWORK</span><h2>Four ways to make it yours.</h2></div><span className="desk-muted">Your limits. Every time.</span></div><div className="desk-preset-strip">{automationPresets.map(preset=><Link key={preset.kind} className={`desk-preset-card tone-${preset.color}`} href={`/automations?preview=1&new=${preset.kind}`}><div><span>{preset.label}</span><ArrowUpRight size={16}/></div><StrategyGlyph kind={preset.kind}/><h3>{preset.name}</h3><p>{preset.description}</p></Link>)}</div></section>
  </div>;
}
