import type { Strategy } from "./types";
export const demoStrategies: Strategy[] = [
  {
    id: "preview-1",
    name: "Buy the NVIDIA dip",
    symbol: "NVDAc",
    rule: "Buy $100 when NVDAc falls below $220",
    mode: "manual",
    status: "armed",
    spent: "200",
    lifetime: "1000",
    orders: 2,
    created_at: "2026-09-04T08:00:00Z",
    last_tick_at: "2026-09-05T08:00:00Z",
    execution_available: false,
  },
  {
    id: "preview-2",
    name: "A little more Apple",
    symbol: "AAPLc",
    rule: "Buy $50 when AAPLc falls below $230",
    mode: "manual",
    status: "armed",
    spent: "150",
    lifetime: "500",
    orders: 3,
    created_at: "2026-09-03T08:00:00Z",
    last_tick_at: "2026-09-05T08:00:00Z",
    execution_available: false,
  },
  {
    id: "preview-3",
    name: "Watching Alphabet",
    symbol: "GOOGLc",
    rule: "Notify when GOOGLc moves above $210",
    mode: "manual",
    status: "paused",
    spent: "0",
    lifetime: "500",
    orders: 0,
    created_at: "2026-09-02T08:00:00Z",
    last_tick_at: null,
    execution_available: false,
  },
];
