import { expect, test } from "bun:test";
import { createRequire } from "node:module";
import { loadWorkerConfig } from "../../config/src/index.js";
import { loggerOptions, secretPaths } from "../src/index.js";

/**
 * What the redaction configuration actually removes, run through the logger that ships.
 *
 * A path list is only a claim. `redact.paths` is compiled by pino's redactor into a stringifier
 * per top-level key, and whether a given path matches a given object is a property of that
 * compiler — not of anything readable in this package. So every assertion here goes through a
 * real pino instance writing to a real stream, and reads the bytes that came out. Asserting on
 * the options object alone would test that we wrote down what we wrote down.
 *
 * Two of these tests assert that something IS printed. They are not oversights: they are the
 * boundary of what path-based redaction can do, and the reason @mandate/execution carries a
 * value-based `Redactor` as well.
 */

interface LogStream {
  write(chunk: string): void;
}
interface Logger {
  info(fields: Record<string, unknown>, message?: string): void;
  child(bindings: Record<string, unknown>): Logger;
}
/** `base` and `timestamp` are ours, to make each line deterministic; the rest is under test. */
type PinoOptions = ReturnType<typeof loggerOptions> & { base?: null; timestamp?: boolean };
type Pino = (options: PinoOptions, destination: LogStream) => Logger;

/**
 * pino, borrowed from the workspace that owns it.
 *
 * @mandate/observability deliberately declares no dependency on pino: it exports an options
 * object, and the consumer supplies the logger — which is what lets the API get its instance
 * from Fastify while the worker constructs its own. The cost is that `import pino from "pino"`
 * does not resolve from this package, and the version under test has to be borrowed from
 * @mandate/worker, whose `pino(loggerOptions(...))` call is the exact thing being verified.
 * Borrowing beats pinning a copy here: this way the test tracks the version that actually runs.
 */
const pino: Pino = (() => {
  const owner = new URL("../../../apps/worker/package.json", import.meta.url);
  try {
    return createRequire(owner)("pino") as Pino;
  } catch (error) {
    // Deliberately not skipped. A redaction test that quietly disappears when a dependency
    // moves is worse than no test: the suite stays green while the guarantee is gone.
    throw new Error("pino did not resolve through apps/worker; run `bun install` first", {
      cause: error,
    });
  }
})();

/** A logger writing into an array, so a test can assert on the exact line pino emitted. */
function capture(level = "info") {
  const lines: string[] = [];
  const log = pino(
    { ...loggerOptions(level), base: null, timestamp: false },
    {
      write(chunk) {
        lines.push(chunk);
      },
    },
  );
  return { log, lines, last: () => lines.at(-1) ?? "" };
}

// A real-shaped throwaway key: 32 bytes that have never held anything and never sign.
const KEY = `0x${"11".repeat(32)}`;

test("the path list compiles, and the censor is the one the runbooks grep for", () => {
  // An invalid redact path is not a lint failure, it throws when pino compiles it — which for
  // the API is inside `buildApp`, in production, at boot. This construction is that compile.
  const { log, last } = capture();
  log.info({ privateKey: KEY }, "started");
  expect(JSON.parse(last())).toEqual({ level: 30, privateKey: "[REDACTED]", msg: "started" });

  expect(loggerOptions("debug").level).toBe("debug");
  // The censor is a function now, so that a credential-bearing URL can keep its origin. What the
  // runbooks actually grep for is the string in the OUTPUT, asserted above and again here —
  // pinning the option's type instead would pass while the logs said something else entirely.
  expect(JSON.parse(last())).toMatchObject({ privateKey: "[REDACTED]" });
  // The list is generated by expanding each secret name over four depths. A name listed twice
  // would produce duplicate paths, which is a sign the generator was edited by hand.
  expect(new Set(secretPaths).size).toBe(secretPaths.length);
});

/**
 * The shape this exists for: a class holds its config, something logs the class.
 *
 * `WorkerChain` is declared `constructor(private readonly config: WorkerConfig, …)`, and
 * TypeScript's `private` is erased at runtime — `config` is an ordinary enumerable property, so
 * `log.info({ chain })` serialises `chain.config.privateKey`. Pino's paths are root-anchored, so
 * the plain name `privateKey` would not have matched any of these.
 */
test("a secret is censored at the root and up to three levels below it", () => {
  const { log, lines, last } = capture();
  log.info({ privateKey: KEY }, "root");
  log.info({ config: { privateKey: KEY } }, "one deep");
  log.info({ chain: { config: { privateKey: KEY } } }, "two deep");
  log.info({ worker: { chain: { config: { privateKey: KEY } } } }, "three deep");
  for (const line of lines) expect(line).not.toContain(KEY.slice(2));
  expect(JSON.parse(last())).toEqual({
    level: 30,
    worker: { chain: { config: { privateKey: "[REDACTED]" } } },
    msg: "three deep",
  });

  // Every name on the list gets the same treatment, at every one of those depths.
  for (const name of ["signature", "spenderKey", "databaseUrl", "anthropicKey"]) {
    const nested = capture();
    nested.log.info({ a: { b: { [name]: "leaked" } } }, "nested");
    expect(nested.last()).not.toContain("leaked");
  }

  // Arrays are objects to the redactor, so a list of signed intents is covered too.
  const array = capture();
  array.log.info({ intents: [{ signature: "0xsig" }] }, "batch");
  expect(array.last()).not.toContain("0xsig");
});

/**
 * The bound, stated as a test rather than left in a comment.
 *
 * Pino has no unbounded-depth wildcard, so the sweep is `*.` repeated up to three times. A
 * secret four levels down is printed in full. Nothing in this codebase logs a shape that deep
 * today, which is what makes three the chosen depth — but if that changes, or if someone raises
 * the depth, this assertion is the one that has to be updated, and that is the point of it.
 *
 * The real defence remains not putting secrets in log objects at all; `SpenderKey` in
 * @mandate/execution keeps its material in a `#` field precisely so no depth of sweep is needed.
 */
test("the wildcard sweep stops four levels down, and a secret there is printed in full", () => {
  const { log, last } = capture();
  log.info({ a: { worker: { chain: { config: { privateKey: KEY } } } } }, "four deep");
  expect(last()).toContain(KEY);
  expect(last()).not.toContain("[REDACTED]");
});

/**
 * Child bindings are stringified once, when the child is created, by a different code path
 * (`asChindings`) than log-time fields. A logger created as `log.child({ config })` and reused
 * for the life of a request would otherwise carry the secret in every line it ever writes.
 */
test("child bindings are redacted the same way as fields on the call", () => {
  const { log, last } = capture();
  log.child({ config: { privateKey: KEY }, instance: "abc" }).info({}, "claimed");
  expect(last()).not.toContain(KEY.slice(2));
  expect(JSON.parse(last())).toEqual({
    level: 30,
    config: { privateKey: "[REDACTED]" },
    instance: "abc",
    msg: "claimed",
  });
});

/**
 * The two packages, checked against each other.
 *
 * `loadWorkerConfig` returns the signing key and the database URL as plain string properties, so
 * the names it chooses for them are the only thing standing between a logged config object and a
 * key in a log aggregator. If a field there is ever renamed — `privateKey` to `signerKey`, say —
 * the redaction list stops matching and nothing else in the build would notice.
 */
test("a whole worker configuration can be logged without printing its secrets", () => {
  const config = loadWorkerConfig({
    DATABASE_URL: "postgres://mandate_app:hunter2@localhost:5432/mandate",
    WORKER_EXECUTE: "1",
    WORKER_PRIVATE_KEY: KEY,
    SPENDER_ADDRESS: `0x${"22".repeat(20)}`,
  });
  const { log, last } = capture();
  log.info({ config }, "worker started");
  expect(last()).not.toContain(KEY.slice(2)); // the signer
  expect(last()).not.toContain("hunter2"); // the database password, inside databaseUrl
  // Public facts survive, or the log would be useless: this is redaction, not suppression.
  expect(JSON.parse(last())).toMatchObject({
    config: { execute: true, spender: `0x${"22".repeat(20)}`, confirmations: 3 },
  });
});

/**
 * The endpoint is a credential, and it keeps its origin.
 *
 * BASE_RPC_URL is validated only as an HTTP(S) URL, and every hosted Base provider embeds its API
 * key in it — Alchemy as a path segment, Helius as a query parameter — so a logged config used to
 * print a billable, rate-limited key. It is redacted now, but by origin rather than wholesale:
 * "which provider, which network" is the first question when the chain is slow, and answering it
 * costs nothing once the key is gone.
 */
test("an RPC endpoint keeps its origin and loses its key", () => {
  const config = loadWorkerConfig({
    DATABASE_URL: "postgres://u:p@localhost:5432/mandate",
    BASE_RPC_URL: "https://base-mainnet.example.com/v2/rpc-api-key",
  });
  const { log, last } = capture();
  log.info({ config }, "worker started");
  expect(last()).not.toContain("rpc-api-key");
  expect(last()).toContain("https://base-mainnet.example.com/[REDACTED]");
  // A non-URL secret has no safe prefix, so it goes entirely.
  expect(last()).toContain('"databaseUrl":"[REDACTED]"');
});

/**
 * Redaction reads fields, so anything that is not a field is untouched: the message string, and
 * every string an upstream library folded into an error. viem writes the JSON-RPC request body
 * into `error.message`, and a signed transaction lives in that body — which is the whole reason
 * @mandate/execution scrubs by VALUE before anything reaches a logger.
 */
test("nothing in the message or an error is redacted, only named fields", () => {
  const { log, lines } = capture();
  log.info({}, `submitting with ${KEY}`);
  expect(lines[0]).toContain(KEY);

  log.info({ err: new Error(`eth_sendRawTransaction failed for ${KEY}`) }, "submit failed");
  expect(lines[1]).toContain(KEY);
});

/**
 * The request envelope. Under Fastify these keys are rewritten by its `req`/`res` serializers
 * before the redactor sees them — and those serializers already drop headers and bodies — so
 * these paths are the net for the plain-pino path the worker uses, and for any handler that
 * logs a request-shaped object of its own.
 */
test("request and response envelopes are censored whole", () => {
  const { log, last } = capture();
  log.info(
    {
      req: {
        headers: {
          cookie: "mandate_session=abc",
          authorization: "Bearer jwt",
          "x-mandate-csrf": "t",
        },
        body: { signature: "0xdeadbeef" },
      },
      res: { headers: { "set-cookie": "mandate_session=abc" } },
      body: { typed_data: { message: "0x" } },
    },
    "request",
  );
  const line = last();
  for (const secret of ["mandate_session=abc", "Bearer jwt", "0xdeadbeef"])
    expect(line).not.toContain(secret);
  expect(JSON.parse(line)).toEqual({
    level: 30,
    req: {
      headers: {
        cookie: "[REDACTED]",
        authorization: "[REDACTED]",
        "x-mandate-csrf": "[REDACTED]",
      },
      body: "[REDACTED]",
    },
    res: { headers: { "set-cookie": "[REDACTED]" } },
    body: "[REDACTED]",
    msg: "request",
  });
});

test("LOG_LEVEL silent writes nothing at all", () => {
  // `silent` is a valid LOG_LEVEL in @mandate/config, and the tests that build an app rely on it
  // producing no output rather than merely a high threshold.
  const { log, lines } = capture("silent");
  log.info({ privateKey: KEY }, "quiet");
  expect(lines).toEqual([]);
});
