"use client";
import { ArrowDownLeft, ArrowUpRight, Check, Clock3, X } from "lucide-react";
import { useState } from "react";
import { useDesk } from "../../providers/desk-provider";
import { StockLogo } from "../market/stock-logo";
import { demoQuote, usd } from "./market-data";
export function OrdersTable(){const {state,cancel}=useDesk();const [tab,setTab]=useState("Open orders");const open=state.orders.filter(o=>o.status==="open");const rows=tab==="Open orders"?open:state.orders;
  return <section className="desk-surface orders-panel"><div className="desk-table-tabs">{["Open orders","Order history","Positions"].map(t=><button type="button" key={t} onClick={()=>setTab(t)} aria-pressed={tab===t} className={tab===t?"active":""}>{t}{t==="Open orders"&&<span>{open.length}</span>}</button>)}<span>Paper account</span></div><div className="desk-table-scroll">{tab==="Positions"?<table className="desk-table"><thead><tr><th>Asset</th><th>Quantity</th><th>Average entry</th><th>Value</th><th>Unrealized P&amp;L</th></tr></thead><tbody>{state.holdings.map(h=>{const value=Math.round(h.quantityUnits*demoQuote(h.symbol,state.tick)/1e6);return <tr key={h.symbol}><td><span className="desk-asset-cell"><StockLogo symbol={h.symbol} small/>{h.symbol}</span></td><td>{(h.quantityUnits/1e6).toFixed(4)}</td><td>{usd(h.costCents/(h.quantityUnits/1e6))}</td><td>{usd(value)}</td><td className={value>=h.costCents?"desk-positive":"desk-negative"}>{usd(value-h.costCents)}</td></tr>;})}</tbody></table>:rows.length?<table className="desk-table"><thead><tr><th>Market</th><th>Side / type</th><th>Amount</th><th>Price</th><th>Status</th><th>Time</th><th/></tr></thead><tbody>{rows.map(order=><tr key={order.id}><td><span className="desk-asset-cell"><StockLogo symbol={order.symbol} small/>{order.symbol}</span></td><td><span className={order.side==="buy"?"desk-positive":"desk-negative"}>{order.side==="buy"?<ArrowDownLeft size={12}/>:<ArrowUpRight size={12}/>} {order.side}</span><small>{order.kind}</small></td><td>{usd(order.amountCents)}</td><td>{usd(order.priceCents)}</td><td><span className={`desk-status ${order.status}`}><i/>{order.status}</span></td><td>{new Date(order.createdAt).toLocaleTimeString("en-US",{hour:"2-digit",minute:"2-digit"})}</td><td>{order.status==="open"?<button type="button" className="desk-icon-button" aria-label={`Cancel ${order.symbol} order`} onClick={()=>cancel(order.id)}><X size={15}/></button>:order.status==="filled"?<Check size={15}/>:null}</td></tr>)}</tbody></table>:<div className="desk-empty"><span className="desk-empty-icon"><Clock3 size={22}/></span><h3>{tab==="Open orders"?"Nothing waiting in the wings.":"Your next move starts here."}</h3><p>{tab==="Open orders"?"Limit and stop orders will appear here.":"Paper trades and cancellations are recorded here."}</p></div>}</div></section>;
}
